IDENT : Device.DeviceInfo.X_MIKROTIK_SystemIdentity
Serial number: Device.DeviceInfo.SerialNumber
Product class: Device.DeviceInfo.ProductClass
Software version: Device.DeviceInfo.SoftwareVersion
Architecture name: Device.DeviceInfo.X_MIKROTIK_ArchName
UPTIME : Device.DeviceInfo.UpTime
E1 MAC: Device.Ethernet.Interface.1.MACAddress
IP : Device.IP.Interface.1.IPv4Address.1.IPAddress
MASK : Device.IP.Interface.1.IPv4Address.1.SubnetMask
DHCP CLNT IP : Device.DHCPv4.Client.1.IPAddress
DHCP CLNT MASK : Device.DHCPv4.Client.1.SubnetMask
SSID : Device.WiFi.SSID.1.SSID
PASS : Device.WiFi.AccessPoint.1.Security.KeyPassphrase
WIFI Clients SSID 1 : Device.WiFi.AccessPoint.1.AssociatedDeviceNumberOfEntries
WIFI Enable : Device.WiFi.Radio.1.Enable
WIFI Status : Device.WiFi.Radio.1.Status
SSID 2 : Device.WiFi.SSID.2.SSID
PASS 2 : Device.WiFi.AccessPoint.2.Security.KeyPassphrase
Wifi Clients : Device.WiFi.AccessPoint.2.AssociatedDeviceNumberOfEntries
Provisioning Code : Device.DeviceInfo.ProvisioningCode